name: test_form_by_json
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

flutter:
  uses-material-design: true

  assets:
    - assets/test.json
